-- Create test_drive_requests table
CREATE TABLE IF NOT EXISTS public.test_drive_requests (
  request_id INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  inv_id INTEGER NOT NULL,
  account_id INTEGER NOT NULL,
  request_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  preferred_date DATE NOT NULL,
  preferred_time VARCHAR(10) NOT NULL,
  phone_number VARCHAR(20) NOT NULL,
  additional_notes TEXT,
  status VARCHAR(20) DEFAULT 'Pending',
  CONSTRAINT test_drive_requests_pkey PRIMARY KEY (request_id),
  CONSTRAINT fk_inventory FOREIGN KEY (inv_id) 
    REFERENCES public.inventory (inv_id) 
    MATCH SIMPLE ON UPDATE CASCADE ON DELETE CASCADE,
  CONSTRAINT fk_account FOREIGN KEY (account_id) 
    REFERENCES public.account (account_id) 
    MATCH SIMPLE ON UPDATE CASCADE ON DELETE CASCADE
);

-- Add comment to table
COMMENT ON TABLE public.test_drive_requests IS 'Stores customer test drive requests for vehicles';
